#!/bin/bash

if [ -f ~/.ssh/config ]; then
  echo "File ~/.ssh/config exists."
  cat ~/.ssh/config
else
  echo "File ~/.ssh/config does not exist. Creating..."
  echo "
Host git.wey.ink
     Port 10022
     HostName git.wey.ink
     User git
     IdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config
  echo "File ~/.ssh/config created."
  cat ~/.ssh/config
fi


